version: "3.9"
services:
  postgres:
    container_name: my-project
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "mydb"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadm
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: d.lexed@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lexed
    ports:
      - "5050:80"